[package]
name = "penguin_hackmd"
version = "0.1.0"
edition = "2021"


[dependencies]
surf = { version = "2.3.2", features = [ "h1-client" ] }
log = "0.4"
env_logger = "0.9.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
